# Generated by Django 6.0.1 on 2026-02-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=300, unique=True)),
                ('brand', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('size', models.CharField(max_length=300)),
                ('mouth_size', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('current_quantity', models.PositiveIntegerField()),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier')),
            ],
        ),
    ]
